//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo
    {
        public int id { get; set; }
        public string h1 { get; set; }
        public string h11 { get; set; }
        public string h2 { get; set; }
        public string p { get; set; }
        public string b { get; set; }
        public string link { get; set; }
        public string alt { get; set; }
        public string item { get; set; }
        public string cid { get; set; }
    }
}
